imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:  console

# SncRedisBundle Configuration
snc_redis:
    doctrine:
        metadata_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        result_cache:
            client: doctrine
            entity_manager: default
            document_manager: default
        query_cache:
            client: doctrine
            entity_manager: default
            document_manager: default